brew "gcc" if OS.linux?

# System-level (linked libraries or complex deps)
brew "coreutils"
brew "curl"
brew "git"
brew "gnupg"
brew "libyaml"
brew "mise"
brew "neovim"
brew "tmux"

if OS.mac?
  brew "colima"
  brew "docker"
  brew "docker-compose"
  brew "docker-buildx"
  brew "pinentry-mac"
  cask "1password-cli"
  cask "font-hack-nerd-font"
  cask "font-monaspice-nerd-font", args: { force: true }
  cask "ghostty"
  cask "nikitabobko/tap/aerospace", trusted: true
end
