alias aliases="nvim ~/.config/fish/functions/aliases.fish"
alias dots="cd ~/.config"
alias g="git status"
alias gb="git branch"
alias gco="git checkout"
alias gpo="git push origin"
alias gpr="git pull --rebase origin"
alias grbi="git rebase -i"
alias ll="eza -al --git --icons=always"
alias notes="cd /Users/acostanzo/Library/Mobile\ Documents/iCloud~md~obsidian/Documents/Notes && vim"
alias vim="nvim"
