alias aliases="nvim ~/.config/fish/functions/aliases.fish"
alias dots="cd ~/.config"
alias g="git status"
alias gangway="~/Projects/BuoySoftware/Gangway/gangway.py"
alias gco="git checkout"
alias gpo="git push origin"
alias gpr="git pull --rebase origin"
alias grbi="git rebase -i"
alias ngb="ngrok http --scheme=http --scheme=https --domain=spinchoon.ngrok.io 3100"
alias ngw="ngrok http --scheme=http --scheme=https --domain=spinchoon.ngrok.io 3101"
alias ll="eza -al --git --icons=always"
alias lsp="cd ~/Projects/BuoySoftware/Parachute/"
alias lsr="cd ~/Projects/BuoySoftware/BuoyRails/"
alias lsw="cd ~/Projects/BuoySoftware/Wharf/"
alias vim="nvim"
alias z="zellij"
